package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/hoshina-dev/pasta/internal/model"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	return r.categoryService.Create(ctx, input)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	items, err := r.categoryService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Category, len(items))
	for i, c := range items {
		result[i] = &c
	}
	return result, nil
}
