// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type GenerateUploadURLInput struct {
	FileName    string `json:"fileName"`
	ContentType string `json:"contentType"`
}

type Mutation struct {
}

type Query struct {
}

type UploadURLResponse struct {
	UploadURL string `json:"uploadURL"`
	FileKey   string `json:"fileKey"`
}
