// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/google/uuid"
)

type GenerateUploadURLInput struct {
	FileName    string `json:"fileName"`
	ContentType string `json:"contentType"`
}

type Mutation struct {
}

type Optimize3DInput struct {
	SourceURL                 string `json:"sourceURL"`
	DracoCompressionLevel     *int32 `json:"dracoCompressionLevel,omitempty"`
	DracoPositionQuantization *int32 `json:"dracoPositionQuantization,omitempty"`
	DracoTexcoordQuantization *int32 `json:"dracoTexcoordQuantization,omitempty"`
	DracoNormalQuantization   *int32 `json:"dracoNormalQuantization,omitempty"`
	DracoGenericQuantization  *int32 `json:"dracoGenericQuantization,omitempty"`
}

type Optimize3DResponse struct {
	JobID  uuid.UUID `json:"jobID"`
	Status string    `json:"status"`
}

type Query struct {
}

type UploadURLResponse struct {
	UploadURL string `json:"uploadURL"`
	FileKey   string `json:"fileKey"`
}
