package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	validator "github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"github.com/hoshina-dev/pasta/internal/model"
)

// CreatePart is the resolver for the createPart field.
func (r *mutationResolver) CreatePart(ctx context.Context, input model.CreatePartInput) (*model.Part, error) {
	validate := validator.New()
	if err := validate.Struct(input); err != nil {
		return nil, err
	}
	return r.partService.Create(ctx, input)
}

// UpdatePart is the resolver for the updatePart field.
func (r *mutationResolver) UpdatePart(ctx context.Context, id uuid.UUID, input model.UpdatePartInput) (*model.Part, error) {
	validate := validator.New()
	if err := validate.Struct(input); err != nil {
		return nil, err
	}
	return r.partService.Update(ctx, id, input)
}

// DeletePart is the resolver for the deletePart field.
func (r *mutationResolver) DeletePart(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.partService.Delete(ctx, id)
	return err == nil, err
}

// CreateManufacturer is the resolver for the createManufacturer field.
func (r *mutationResolver) CreateManufacturer(ctx context.Context, input model.CreateManufacturerInput) (*model.Manufacturer, error) {
	return r.manufacturerService.Create(ctx, input)
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	return r.categoryService.Create(ctx, input)
}

// Images is the resolver for the images field.
func (r *partResolver) Images(ctx context.Context, obj *model.Part) ([]string, error) {
	return []string(obj.Images), nil
}

// Parts is the resolver for the parts field.
func (r *queryResolver) Parts(ctx context.Context) ([]*model.Part, error) {
	parts, err := r.partService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Part, len(parts))
	for i := range parts {
		result[i] = &parts[i]
	}
	return result, nil
}

// Part is the resolver for the part field.
func (r *queryResolver) Part(ctx context.Context, id uuid.UUID) (*model.Part, error) {
	return r.partService.GetByID(ctx, id)
}

// SearchParts is the resolver for the searchParts field.
func (r *queryResolver) SearchParts(ctx context.Context, name string) ([]*model.Part, error) {
	parts, err := r.partService.Search(ctx, name)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Part, len(parts))
	for i := range parts {
		result[i] = &parts[i]
	}
	return result, nil
}

// Manufacturer is the resolver for the manufacturer field.
func (r *queryResolver) Manufacturer(ctx context.Context, id uuid.UUID) (*model.Manufacturer, error) {
	return r.manufacturerService.GetByID(ctx, id)
}

// Manufacturers is the resolver for the manufacturers field.
func (r *queryResolver) Manufacturers(ctx context.Context) ([]*model.Manufacturer, error) {
	items, err := r.manufacturerService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Manufacturer, len(items))
	for i, m := range items {
		result[i] = &m
	}
	return result, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	items, err := r.categoryService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Category, len(items))
	for i, c := range items {
		result[i] = &c
	}
	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Part returns PartResolver implementation.
func (r *Resolver) Part() PartResolver { return &partResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type partResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
