package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/hoshina-dev/pasta/internal/model"
)

// Status is the resolver for the status field.
func (r *part3DModelResolver) Status(ctx context.Context, obj *model.Part3DModel) (string, error) {
	return string(obj.Status), nil
}

// Part3DModel returns Part3DModelResolver implementation.
func (r *Resolver) Part3DModel() Part3DModelResolver { return &part3DModelResolver{r} }

type part3DModelResolver struct{ *Resolver }
