package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	validator "github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"github.com/hoshina-dev/pasta/internal/model"
)

// CreatePasta is the resolver for the createPasta field.
func (r *mutationResolver) CreatePasta(ctx context.Context, input model.CreatePastaInput) (*model.Pasta, error) {
	validate := validator.New()
	if err := validate.Struct(input); err != nil {
		return nil, err
	}
	return r.pastaService.Create(ctx, input)
}

// UpdatePasta is the resolver for the updatePasta field.
func (r *mutationResolver) UpdatePasta(ctx context.Context, id uuid.UUID, input model.UpdatePastaInput) (*model.Pasta, error) {
	validate := validator.New()
	if err := validate.Struct(input); err != nil {
		return nil, err
	}
	return r.pastaService.Update(ctx, id, input)
}

// DeletePasta is the resolver for the deletePasta field.
func (r *mutationResolver) DeletePasta(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.pastaService.Delete(ctx, id)
	return err == nil, err
}

// CreateManufacturer is the resolver for the createManufacturer field.
func (r *mutationResolver) CreateManufacturer(ctx context.Context, input model.CreateManufacturerInput) (*model.Manufacturer, error) {
	return r.manufacturerService.Create(ctx, input)
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	return r.categoryService.Create(ctx, input)
}

// Images is the resolver for the images field.
func (r *pastaResolver) Images(ctx context.Context, obj *model.Pasta) ([]string, error) {
	return []string(obj.Images), nil
}

// Pastas is the resolver for the pastas field.
func (r *queryResolver) Pastas(ctx context.Context) ([]*model.Pasta, error) {
	pastas, err := r.pastaService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Pasta, len(pastas))
	for i := range pastas {
		result[i] = &pastas[i]
	}
	return result, nil
}

// Pasta is the resolver for the pasta field.
func (r *queryResolver) Pasta(ctx context.Context, id uuid.UUID) (*model.Pasta, error) {
	return r.pastaService.GetByID(ctx, id)
}

// SearchPastas is the resolver for the searchPastas field.
func (r *queryResolver) SearchPastas(ctx context.Context, name string) ([]*model.Pasta, error) {
	pastas, err := r.pastaService.Search(ctx, name)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Pasta, len(pastas))
	for i := range pastas {
		result[i] = &pastas[i]
	}
	return result, nil
}

// Manufacturer is the resolver for the manufacturer field.
func (r *queryResolver) Manufacturer(ctx context.Context, id uuid.UUID) (*model.Manufacturer, error) {
	return r.manufacturerService.GetByID(ctx, id)
}

// Manufacturers is the resolver for the manufacturers field.
func (r *queryResolver) Manufacturers(ctx context.Context) ([]*model.Manufacturer, error) {
	items, err := r.manufacturerService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Manufacturer, len(items))
	for i, m := range items {
		result[i] = &m
	}
	return result, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	items, err := r.categoryService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Category, len(items))
	for i, c := range items {
		result[i] = &c
	}
	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Pasta returns PastaResolver implementation.
func (r *Resolver) Pasta() PastaResolver { return &pastaResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type pastaResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
