package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/google/uuid"
	"github.com/hoshina-dev/pasta/internal/model"
)

// CreatePasta is the resolver for the createPasta field.
func (r *mutationResolver) CreatePasta(ctx context.Context, input CreatePastaInput) (*model.Pasta, error) {
	return r.PastaService.Create(ctx, input.Name, input.Description, input.Price)
}

// UpdatePasta is the resolver for the updatePasta field.
func (r *mutationResolver) UpdatePasta(ctx context.Context, id uuid.UUID, input UpdatePastaInput) (*model.Pasta, error) {
	return r.PastaService.Update(ctx, id, input.Name, input.Description, input.Price)
}

// DeletePasta is the resolver for the deletePasta field.
func (r *mutationResolver) DeletePasta(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.PastaService.Delete(ctx, id)
	return err == nil, err
}

// Pastas is the resolver for the pastas field.
func (r *queryResolver) Pastas(ctx context.Context) ([]*model.Pasta, error) {
	pastas, err := r.PastaService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Pasta, len(pastas))
	for i := range pastas {
		result[i] = &pastas[i]
	}
	return result, nil
}

// Pasta is the resolver for the pasta field.
func (r *queryResolver) Pasta(ctx context.Context, id uuid.UUID) (*model.Pasta, error) {
	return r.PastaService.GetByID(ctx, id)
}

// SearchPastas is the resolver for the searchPastas field.
func (r *queryResolver) SearchPastas(ctx context.Context, name string) ([]*model.Pasta, error) {
	pastas, err := r.PastaService.Search(ctx, name)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Pasta, len(pastas))
	for i := range pastas {
		result[i] = &pastas[i]
	}
	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
