package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/hoshina-dev/pasta/internal/service"
)

// Optimize3d is the resolver for the optimize3D field.
func (r *mutationResolver) Optimize3d(ctx context.Context, input Optimize3DInput) (*Optimize3DResponse, error) {
	params := service.Optimize3DParams{
		SourceURL:                 input.SourceURL,
		DracoCompressionLevel:     input.DracoCompressionLevel,
		DracoPositionQuantization: input.DracoPositionQuantization,
		DracoTexcoordQuantization: input.DracoTexcoordQuantization,
		DracoNormalQuantization:   input.DracoNormalQuantization,
		DracoGenericQuantization:  input.DracoGenericQuantization,
	}

	jobID, status, err := r.Resolver.optimizationService.Optimize3D(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to start optimization job: %w", err)
	}

	return &Optimize3DResponse{
		JobID:  jobID,
		Status: status,
	}, nil
}

// GenerateUploadURL is the resolver for the generateUploadURL field.
func (r *queryResolver) GenerateUploadURL(ctx context.Context, input GenerateUploadURLInput) (*UploadURLResponse, error) {
	uploadURL, fileKey, err := r.Resolver.storageService.GenerateUploadURL(ctx, input.FileName, input.ContentType)
	if err != nil {
		return nil, fmt.Errorf("failed to generate upload URL: %w", err)
	}

	return &UploadURLResponse{
		UploadURL: uploadURL,
		FileKey:   fileKey,
	}, nil
}
