package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
)

// GenerateUploadURL is the resolver for the generateUploadURL field.
func (r *queryResolver) GenerateUploadURL(ctx context.Context, input GenerateUploadURLInput) (*UploadURLResponse, error) {
	uploadURL, fileKey, err := r.Resolver.storageService.GenerateUploadURL(ctx, input.FileName, input.ContentType)
	if err != nil {
		return nil, fmt.Errorf("failed to generate upload URL: %w", err)
	}

	return &UploadURLResponse{
		UploadURL: uploadURL,
		FileKey:   fileKey,
	}, nil
}
