-- Revoke default privileges
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE ON TABLES FROM pasta_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE USAGE ON SEQUENCES FROM pasta_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE EXECUTE ON FUNCTIONS FROM pasta_rw;

-- Revoke privileges on existing objects
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM pasta_rw;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM pasta_rw;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM pasta_rw;
REVOKE USAGE ON SCHEMA public FROM pasta_rw;
REVOKE CONNECT ON DATABASE pasta FROM pasta_rw;

-- Drop the role
DROP ROLE IF EXISTS pasta_rw;
